/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_segmentDialog (void);
GtkWidget* create_app1 (void);
GtkWidget* create_inputDialog (void);
GtkWidget* create_dialogAdvanced (void);
GtkWidget* create_ImageSetupDialog (void);
GtkWidget* create_setupDialog (void);
GtkWidget* create_aboutdialog1 (void);
GtkWidget* create_calculatingDialog (void);
